title: Notre-Dame de Paris
baseURL: https://gohugo-theme-ananke.pages.dev
languageCode: en-us
theme: gohugo-theme-ananke
resourceDir: ../resources
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: yes
languages:
  en:
    contentDir: content/en
    title: Razor_Z_Pi 
    weight: 1
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
params:
  author: ''
  background_color_class: bg-black
  description: Hi users.
  favicon: ''
  recent_posts_number: 3
  site_logo: ''
  text_color: ''
